// @ts-check
import { resolve, sep } from 'node:path';

/**
 * Resolve `filepath` against `projectRoot` and refuse paths that escape it. A
 * bare `startsWith` would let a sibling directory sharing the root's name prefix
 * through (e.g. "/proj" vs "/proj-secrets"), so require an exact match or a real
 * path-separator boundary.
 * @param {string} projectRoot
 * @param {string} filepath
 * @returns {string} absolute path inside the project root
 */
export function resolveWithinRoot(projectRoot, filepath) {
  const root = resolve(projectRoot);
  const outPath = resolve(root, filepath);
  if (outPath !== root && !outPath.startsWith(root + sep)) {
    throw new Error(`astro-aeo: urlMap.outputFilepath escapes the project root: ${filepath}`);
  }
  return outPath;
}

/**
 * Write a Markdown table of every page to a file under the project root
 * (default docs/Url-Map.md), for committing as a content audit.
 *
 * @param {import('../build/collect.js').PageInfo[]} pages
 * @param {import('../index.js').ResolvedAstroAeoConfig} config
 * @param {string} projectRoot
 * @param {Date} generatedAt
 * @param {ReturnType<typeof import('../build/artifacts.js').createArtifactWriter>} writer
 * @returns {boolean} whether the URL map was written
 */
export function emitUrlMap(pages, config, projectRoot, generatedAt, writer) {
  if (!config.corpus.urlMap.enabled) return false;

  // Validate confinement before handing the path to the shared registry. The
  // URL map intentionally lives under the project root rather than dist, but it
  // must still participate in cross-generator ownership checks.
  const outPath = resolveWithinRoot(projectRoot, config.corpus.urlMap.outputFilepath);

  const stamp = generatedAt.toISOString().slice(0, 19).replace('T', ' at ');
  const lines = [
    '# Url Map',
    `Generated by astro-aeo on ${stamp}`,
    '',
    '## Pages',
    '',
    '| URL | Markdown | Title | Last modified |',
    '| --- | --- | --- | --- |',
  ];

  for (const p of pages) {
    const lm = p.lastModified ? p.lastModified.slice(0, 10) : '';
    lines.push(`| ${cell(p.pathname)} | ${cell(p.mdHref)} | ${cell(p.title)} | ${cell(lm)} |`);
  }

  return writer.write({
    path: outPath,
    owner: 'urlMap',
    contents: `${lines.join('\n')}\n`,
    // Historical behaviour is an unconditional, silent replacement.
    onConflict: 'overwrite',
  });
}

/**
 * @param {string} value
 * @returns {string}
 */
function cell(value) {
  return value.replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}
