// @ts-check
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

/**
 * Write a Markdown table of every page to a file under the project root
 * (default docs/Url-Map.md), for committing as a content audit.
 *
 * @param {import('../lib/collect.js').PageInfo[]} pages
 * @param {import('../index.js').ResolvedAeoConfig} config
 * @param {string} projectRoot
 * @param {Date} generatedAt
 */
export function emitUrlMap(pages, config, projectRoot, generatedAt) {
  if (!config.urlMap.enabled) return;

  const outPath = resolve(projectRoot, config.urlMap.outputFilepath);
  // Refuse to write outside the project root.
  if (!outPath.startsWith(resolve(projectRoot))) {
    throw new Error(`astro-aeo: urlMap.outputFilepath escapes the project root: ${config.urlMap.outputFilepath}`);
  }

  const stamp = generatedAt.toISOString().slice(0, 19).replace('T', ' at ');
  const lines = [
    '# Url Map',
    `Generated by astro-aeo on ${stamp}`,
    '',
    '## Pages',
    '',
    '| URL | Markdown | Title | Last modified |',
    '| --- | --- | --- | --- |',
  ];

  for (const p of pages) {
    const lm = p.lastModified ? p.lastModified.toISOString().slice(0, 10) : '';
    lines.push(`| ${cell(p.pathname)} | ${cell(p.mdHref)} | ${cell(p.title)} | ${cell(lm)} |`);
  }

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, `${lines.join('\n')}\n`, 'utf8');
}

/**
 * @param {string} value
 * @returns {string}
 */
function cell(value) {
  return value.replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}
